const dummyPopularCategories = {
  categories: [
    "baby",
    "computer",
    "baby",
    "computer",
    "baby",
    "seat",
    "baby",
    "computer",
    "baby",
    "desktop",
    "hub & router",
    "repeater",
    "car",
    "electornics",
  ],
};

const dummyPopularBrands = {
  brands: [
    "A-stream",
    "gitck",
    "bic burket",
    "steam link",
    "start company",
    "good kickhen",
    "egg drop",
    "bit coin",
    "centons",
    "ubuntu",
    "fadora",
    "red hat",
    "stop this",
    "pinao porte",
    "electronic guitar",
    "all about machine",
    "dont look up",
    "victim",
    "find someone and",
    "good service company",
    "action movie creator",
    "actors party",
    "cretical damage",
    "will you write",
    "no i dont have",
    "A-stream",
    "gitck",
    "bic burket",
    "steam link",
    "start company",
    "good kickhen",
    "egg drop",
    "bit coin",
    "centons",
    "ubuntu",
    "fadora",
    "red hat",
    "stop this record",
    "pinao porte",
    "electronic guitar",
    "all about machine",
    "dont look up",
    "victim",
    "find someone and",
    "good service company",
    "action movie creator",
    "actors party",
    "cretical damage",
    "will you write ",
    "no i dont have ",
    "bit coin",
    "centons",
    "ubuntu",
    "fadora",
    "red hat",
    "stop this record",
    "pinao porte",
    "electronic guitar",
    "all about machine",
    "dont look up",
    "look up me",
  ],
};
const dummyBrandCategories = {
  brands: [
    "A-stream",
    "gitck",
    "bic burket",
    "steam link",
    "start company",
    "good kickhen",
    "egg drop",
    "bit coin",
    "centons",
    "ubuntu",
    "fadora",
    "red hat",
    "stop this record",
    "pinao porte",
    "electronic guitar",
    "all about machine",
    "dont look up",
    "victim",
    "find someone and",
    "good service company",
    "action movie creator",
    "actors party",
    "cretical damage",
    "will you write",
    "no i dont have",
    "A-stream",
    "gitck",
    "bic burket",
    "steam link",
    "start company",
    "good kickhen",
    "egg drop",
    "bit coin",
    "centons",
    "ubuntu",
    "fadora",
    "red hat",
    "stop this record",
    "pinao porte",
    "electronic guitar",
    "all about machine",
    "dont look up",
    "victim",
    "find someone and",
    "good service company",
    "action movie creator",
    "actors party",
    "cretical damage",
    "will you write",
    "no i dont have",
    "bit coin",
    "centons",
    "ubuntu",
    "fadora",
    "red hat",
    "stop this record",
    "pinao porte",
    "electronic guitar",
    "all about machine",
    "dont look up",
    "look up me",
    "A-stream",
    "gitck",
    "bic burket",
    "steam link",
    "start company",
    "good kickhen",
    "egg drop",
    "bit coin",
    "centons",
    "ubuntu",
    "fadora",
    "red hat",
    "stop this record",
    "pinao porte",
    "electronic guitar",
    "all about machine",
    "dont look up",
    "victim",
    "find someone and",
    "good service company",
    "action movie creator",
    "actors party",
    "cretical damage",
    "will you write",
    "no i dont have",
    "A-stream",
    "gitck",
    "bic burket",
    "steam link",
    "start company",
    "good kickhen",
    "egg drop",
    "bit coin",
    "centons",
    "ubuntu",
    "fadora",
    "red hat",
    "stop this record",
    "pinao porte",
    "electronic guitar",
    "all about machine",
    "dont look up",
    "victim",
    "find someone and",
    "good service company",
    "action movie creator",
    "actors party",
    "cretical damage",
    "will you write",
    "no i dont have",
    "bit coin",
    "centons",
    "ubuntu",
    "fadora",
    "red hat",
    "stop this record",
    "pinao porte",
    "electronic guitar",
    "all about machine",
    "dont look up",
    "look up me",
  ],
};

module.exports = { dummyBrandCategories, dummyPopularBrands, dummyPopularCategories };
