//!
// 1. A#누르면 A#만 오고, AA누르면 AA가 오도록 만든다 (SSG)
// 2. A -> A#~AZ까지 전부다 받아온다 (SPA)

export const AdummyData = {
  category: "A",
  list: [
    {
      "A#": [
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
        "A.T.I.B",
        "A-image",
        "A-ipower",
        "A&R Cambridge Limited",
      ],
    },
  ],
};
